name: evlution_env
dependencies:
  - python=3.7
  - numpy=1.21.5
  - pandas=1.3.4
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - urllib3=1.26.9
  - boto3=1.24.28
  - Shapely=1.7.1
  - Fiona=1.8.13.post1
  - geopandas=0.9.0
  - pip=21.2.4
  - pip:
    - seaborn==0.12.1
    - python-decouple==3.6
    - Mesa==0.9.0
    - SQLAlchemy==1.4.44
    - psycopg2==2.9.5
    - PyMySQL==1.0.2
    - ipykernel==6.16.2
    - plotly==5.11.0
    - streamlit==1.15.2
    - streamlit-option-menu==0.3.2