model_params:
  # POI_file: "fetch_from_database"
  POI_file: "inputs/Isle_of_Wight_poi_data.csv"
  Traffic_file: "None"
  model_name: "Isle_of_Wight"
  rep_agents: 600

agent_params:
  EVs:
    Holiday_Goer:
      num_agents: 140
    Daily_Commuter:
      num_agents: 500
    Taxi_Driver:
      num_agents: 100
  Charge_Points:
    CP_loc: "inputs/Isle_of_Wight_charging_stations.csv"
    perc_in_operation: 0.9
