model_params:
  POI_file: "inputs/Mississauga_poi_data.csv"
  Traffic_file: "None"
  model_name: "Isle_of_Wight"
  rep_agents: 7000

agent_params:
  EVs:
    num_agents: 1000
  Charge_Points:
    CP_loc: "inputs/Isle_of_Wight_charging_stations.csv"
