model_params:
  POI_file: "inputs/Isle_of_Wight_poi_data.csv"
  Traffic_file: "None"
  model_name: "Isle_of_Wight"
  rep_agents: 600

agent_params:
  EVs:
    EV_Type1:
      num_agents: 5
    EV_Type2:
      num_agents: 5
    EV_Type3:
      num_agents: 5
  Charge_Points:
    CP_loc: "inputs/Isle_of_Wight_charging_stations.csv"
    perc_in_operation: 0.8
