model_params: 
  POI_file: 'inputs/bounding_box_1_poi_data.csv'
  Traffic_file: 'None'
  model_name :  'Rural West'
  rep_agents: 2250

agent_params: 
  EVs: 
    num_agents: 1000
  Charge_Points:
    CP_loc: 'inputs/bounding_box_1_charging_stations.csv'
